---
swagger: "2.0"
info:
  description: "This is an API for a football tournament"
  version: "1.0.0"
  title: "Soccer Tournament API"
  contact:
    email: "hugo.mario.mercado@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "dev-virtserver.swaggerhub.com"
basePath: "/hugom/newone/1.0.0"
tags:
- name: "admins"
  description: "Secured Admin-only calls"
- name: "developer"
  description: "Operations available to regular developers"
schemes:
- "https"
paths:
  /team:
    get:
      tags:
      - "public operations"
      summary: "get a team"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ teams in the system\n"
      operationId: "getTeam"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "pass an optional team name."
        required: false
        type: "string"
      - name: "skip"
        in: "query"
        description: "number of records to skip for pagination"
        required: false
        type: "integer"
        minimum: 0.0
        format: "int32"
      - name: "limit"
        in: "query"
        description: "maximum number of records to return"
        required: false
        type: "integer"
        maximum: 50.0
        minimum: 0.0
        format: "int32"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Team"
        400:
          description: "bad input parameter"
    post:
      tags:
      - "admin operations"
      summary: "adds a team"
      description: "Adds a team to the system"
      operationId: "addTeam"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "inventoryItem"
        description: "Inventory item to add"
        required: false
        schema:
          $ref: "#/definitions/Team"
      responses:
        201:
          description: "item created"
        400:
          description: "invalid input, object invalid"
        409:
          description: "an existing item already exists"
definitions:
  Team:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      name:
        type: "string"
        example: "AC Milan"
      coach:
        $ref: "#/definitions/Coach"
  Coach:
    required:
    - "name"
    properties:
      name:
        type: "string"
        example: "Diego Simeone"
      homePage:
        type: "string"
        format: "url"
        example: "https://www.acme-corp.com"
